// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndpeeebvtdossqdxdcsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kcGVlZWJ2dGRvc3NxZHhkY3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NTE0ODEsImV4cCI6MjA2NTMyNzQ4MX0.oTixSh85lanv0QmBJxfrz5hWvnSNEo7grjO3mJ3rc08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);